var sphere;
var sphereAnim;
var box;
var rotation;
var hold = 0;
var jet = 0;
var pv = 3;
var pv_max = 6;
var lastRoom = -1;
var buttonPressed;
var compSelect = 1;
var blocGrab;
var atk = 0;
var take_hit;
var stick_x1;
var stick_y1;
var stick_x;
var stick_y;
var hitBox;
var mechant;
var fireBoule;
var once;
var un;
var count = 0;
//doors
var key = 0;
var lock1 = 1;
var lock2 = 1;
var lock3 = 1;
var lock4 = 1;
var lock5 = 1;
var lock6 = 1;
var lock7 = 1;
var lock8 = 1;
var lock9 = 1;
//drop par salles
var room1 = 0;
var room10 = 0;